<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="MAIN" Id="{076a6edd-7aae-4d3b-ac7f-5e66ffd1b567}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
	// Bedienparameter
	
	// Rezeptparameter


END_VAR

VAR_INPUT

END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[// Starten der Anlage
Reaktoranlage();

// Starten des Rezeptes
Rezept_1();

GVL_OPC_UA.RZCW_R1.Leitung := 3;]]></ST>
    </Implementation>
    <LineIds Name="MAIN">
      <LineId Id="29" Count="0" />
      <LineId Id="31" Count="0" />
      <LineId Id="30" Count="0" />
      <LineId Id="2" Count="0" />
      <LineId Id="26" Count="0" />
      <LineId Id="44" Count="0" />
      <LineId Id="27" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>