<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="MAIN" Id="{de090dfa-1e55-4b06-8517-c95a5f22bef4}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
	// Bedienparameter
	
	// Rezeptparamter
	
	// Grundfunktionen
	
	// Sonstiges

END_VAR

VAR_INPUT
	// Statusword
	
	// Sonstiges
	Leitung			:FB_Leitungswahl;
END_VAR

]]></Declaration>
    <Implementation>
      <ST><![CDATA[// Starten der Reaktoreinheit
Reaktoreinheit();

// Starten der Auswertung der Kommunikationsschnittstelle
Kommunikation();
]]></ST>
    </Implementation>
    <LineIds Name="MAIN">
      <LineId Id="111" Count="0" />
      <LineId Id="40" Count="0" />
      <LineId Id="113" Count="0" />
      <LineId Id="112" Count="0" />
      <LineId Id="39" Count="0" />
      <LineId Id="74" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>