<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="MAIN" Id="{de090dfa-1e55-4b06-8517-c95a5f22bef4}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
	// Bedienparameter
	
	// Rezeptparamter
	
	// Grundfunktionen
	Entleeren		:GF_Entleeren;
	//Halten			:GF_Halten;
	Pumpen			:GF_Pumpen;
	Zirkulieren		:GF_Zirkulieren;
	Ruehren 		:GF_Ruehren;
	Warten			:GF_Warten;	
	Befuellen		:GF_Befuellen;
	
	// Controlword
	CW		:RezeptControlWord;
	
	// Sonstiges
	
	// Testvariablen
	Check		:BOOL;

END_VAR

VAR_INPUT
	// Statusword
	SW		:RezeptStatusWord;
	
	// Sonstiges
	Leitung			:FB_Leitungswahl;
END_VAR

]]></Declaration>
    <Implementation>
      <ST><![CDATA[Reaktoreinheit();
//Auswertung_Alt();
Auswertung();]]></ST>
    </Implementation>
    <LineIds Name="MAIN">
      <LineId Id="40" Count="0" />
      <LineId Id="2" Count="0" />
      <LineId Id="39" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>