<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="MAIN" Id="{d5feccea-6762-47e0-99a4-b2697d0f6092}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
	Check			:BOOL;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[Anlage();]]></ST>
    </Implementation>
    <LineIds Name="MAIN">
      <LineId Id="12" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>